export interface SummaryExportOptions {
  title: string;
  workspaceName?: string;
  generatedBy?: string;
  generatedAt?: string;
  periodText?: string;
  filtersText?: string;
  totalRevenue: number;
  totalLeads: number;
  userStats: Array<{
    userId: string;
    name: string;
    role: string;
    department: string;
    branch: string;
    leadsCreated: number;
    revenueGenerated: number;
  }>;
}

const formatCurrency = (val: number): string => {
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
    maximumFractionDigits: 0,
  }).format(val || 0);
};

/**
 * Generates a dedicated multi-page PDF document for Summary Activity & Performance Reports.
 */
export const generateSummaryReportPdfReport = (options: SummaryExportOptions): string => {
  const {
    title = 'Activity Reports',
    workspaceName = 'Seeakk Workspace',
    generatedBy = 'System User',
    generatedAt = new Date().toLocaleString(),
    periodText = 'All Time',
    filtersText = 'All Users',
    totalRevenue = 0,
    totalLeads = 0,
    userStats = [],
  } = options;

  const rowsHtml = userStats
    .map(
      (user, idx) => `
    <tr style="border-bottom: 1px solid #f1f5f9;">
      <td style="padding: 10px 14px; font-weight: 900; color: #94a3b8; width: 60px;">#${idx + 1}</td>
      <td style="padding: 10px 14px; font-weight: 800; color: #0f172a;">${user.name || 'Unknown User'}</td>
      <td style="padding: 10px 14px; color: #475569; font-weight: 600;">${user.role || '-'}</td>
      <td style="padding: 10px 14px; color: #475569; font-weight: 600;">${user.branch || '-'}</td>
      <td style="padding: 10px 14px; text-align: center; font-weight: 800; color: #0f172a;">${user.leadsCreated.toLocaleString()}</td>
      <td style="padding: 10px 14px; text-align: right; font-weight: 900; color: #059669;">${formatCurrency(user.revenueGenerated)}</td>
    </tr>`,
    )
    .join('');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${title} — Multi-Page PDF Document</title>
  <style>
    @page { size: portrait; margin: 12mm; }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; background-color: #ffffff; color: #1e293b; padding: 0; }
    .header { display: flex; align-items: center; justify-content: space-between; border-bottom: 3px solid #6366f1; padding-bottom: 14px; margin-bottom: 20px; }
    .logo-title { display: flex; align-items: center; gap: 12px; }
    .badge-logo { background: #6366f1; color: white; width: 38px; height: 38px; border-radius: 10px; display: flex; align-items: center; justify-content: center; font-weight: 900; font-size: 18px; }
    .title { font-size: 20px; font-weight: 900; color: #0f172a; }
    .subtitle { font-size: 11px; color: #64748b; font-weight: 600; margin-top: 2px; }
    .meta-box { text-align: right; font-size: 10px; color: #64748b; line-height: 1.5; }
    .filters-bar { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 10px; padding: 10px 14px; margin-bottom: 20px; font-size: 11px; color: #475569; display: flex; gap: 20px; }
    .cards-grid { display: flex; gap: 14px; margin-bottom: 24px; }
    .card { flex: 1; border-radius: 12px; padding: 14px 16px; border: 1px solid #e0e7ff; background: linear-gradient(135deg, #e0e7ff 0%, #eef2ff 100%); }
    .card-emerald { border-color: #a7f3d0; background: linear-gradient(135deg, #ecfdf5 0%, #f0fdf4 100%); }
    .card-label { font-size: 10px; font-weight: 800; text-transform: uppercase; letter-spacing: 0.5px; color: #3730a3; }
    .card-val { font-size: 24px; font-weight: 900; color: #4338ca; margin-top: 4px; }
    .table-container { width: 100%; border: 1px solid #e2e8f0; border-radius: 12px; overflow: hidden; margin-bottom: 20px; }
    table { width: 100%; border-collapse: collapse; font-size: 12px; text-align: left; }
    thead { display: table-header-group; }
    tr { page-break-inside: avoid; }
    thead th { background-color: #f8fafc; border-bottom: 2px solid #e2e8f0; padding: 10px 14px; font-size: 10px; font-weight: 800; color: #475569; text-transform: uppercase; letter-spacing: 0.5px; }
    footer { text-align: center; margin-top: 24px; font-size: 10px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 14px; }
  </style>
</head>

<body onload="window.print()">
  <div class="header">
    <div class="logo-title">
      <div class="badge-logo">S</div>
      <div>
        <div class="title">SEEAKK — ${title}</div>
        <div class="subtitle">Company-Wide Performance, Revenue & User Activity Analytics</div>
      </div>
    </div>
    <div class="meta-box">
      <div><strong>Workspace:</strong> ${workspaceName}</div>
      <div><strong>Generated By:</strong> ${generatedBy}</div>
      <div><strong>Generated At:</strong> ${generatedAt}</div>
    </div>
  </div>

  <div class="filters-bar">
    <div><strong>Period:</strong> ${periodText}</div>
    <div><strong>Applied Filters:</strong> ${filtersText}</div>
    <div><strong>Total Users Included:</strong> ${userStats.length} user(s)</div>
  </div>

  <!-- Summary Cards -->
  <div class="cards-grid">
    <div class="card">
      <div class="card-label">Total Revenue Generated</div>
      <div class="card-val">${formatCurrency(totalRevenue)}</div>
    </div>
    <div class="card card-emerald">
      <div class="card-label" style="color: #065f46;">Total Leads Created</div>
      <div class="card-val" style="color: #047857;">${totalLeads.toLocaleString()}</div>
    </div>
  </div>

  <!-- User Performance Ranking Table -->
  <h3 style="font-size: 13px; font-weight: 800; color: #0f172a; margin-bottom: 10px;">User Performance Ranking</h3>
  <div class="table-container">
    <table>
      <thead>
        <tr>
          <th style="width: 60px;">Rank</th>
          <th>User</th>
          <th>Role</th>
          <th>Branch</th>
          <th style="text-align: center;">Leads Created</th>
          <th style="text-align: right;">Revenue Generated</th>
        </tr>
      </thead>
      <tbody>
        ${userStats.length === 0 ? `<tr><td colSpan="6" style="text-align: center; padding: 24px; color: #94a3b8;">No matching activity found for the selected filters.</td></tr>` : rowsHtml}
      </tbody>
    </table>
  </div>

  <footer>
    SEEAKK — Dynamic Lead Performance Dynamics Platform • Generated ${generatedAt}
  </footer>
</body>
</html>`;
};

/**
 * Generates a standalone Interactive HTML document for Summary Activity Reports.
 */
export const generateSummaryReportHtmlReport = (options: SummaryExportOptions): string => {
  return generateSummaryReportPdfReport(options);
};
